package com.zhao.giftsaydemo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhao.giftsaydemo.db.Strategy;

import com.zhao.giftsaydemo.db.StrategyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig strategyDaoConfig;

    private final StrategyDao strategyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        strategyDaoConfig = daoConfigMap.get(StrategyDao.class).clone();
        strategyDaoConfig.initIdentityScope(type);

        strategyDao = new StrategyDao(strategyDaoConfig, this);

        registerDao(Strategy.class, strategyDao);
    }
    
    public void clear() {
        strategyDaoConfig.getIdentityScope().clear();
    }

    public StrategyDao getStrategyDao() {
        return strategyDao;
    }

}
