package com.zhao.giftsaydemo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhao.giftsaydemo.db.Strategy;
import com.zhao.giftsaydemo.db.Gift;

import com.zhao.giftsaydemo.db.StrategyDao;
import com.zhao.giftsaydemo.db.GiftDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig strategyDaoConfig;
    private final DaoConfig giftDaoConfig;

    private final StrategyDao strategyDao;
    private final GiftDao giftDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        strategyDaoConfig = daoConfigMap.get(StrategyDao.class).clone();
        strategyDaoConfig.initIdentityScope(type);

        giftDaoConfig = daoConfigMap.get(GiftDao.class).clone();
        giftDaoConfig.initIdentityScope(type);

        strategyDao = new StrategyDao(strategyDaoConfig, this);
        giftDao = new GiftDao(giftDaoConfig, this);

        registerDao(Strategy.class, strategyDao);
        registerDao(Gift.class, giftDao);
    }
    
    public void clear() {
        strategyDaoConfig.getIdentityScope().clear();
        giftDaoConfig.getIdentityScope().clear();
    }

    public StrategyDao getStrategyDao() {
        return strategyDao;
    }

    public GiftDao getGiftDao() {
        return giftDao;
    }

}
