package com.zhao.giftsaydemo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GIFT".
 */
public class Gift {

    private Long id;
    private String imgUrl;
    private String name;
    private String taobaoUrl;

    public Gift() {
    }

    public Gift(Long id) {
        this.id = id;
    }

    public Gift(Long id, String imgUrl, String name, String taobaoUrl) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.name = name;
        this.taobaoUrl = taobaoUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTaobaoUrl() {
        return taobaoUrl;
    }

    public void setTaobaoUrl(String taobaoUrl) {
        this.taobaoUrl = taobaoUrl;
    }

}
