package com.zhao.giftsaydemo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STRATEGY".
 */
public class Strategy {

    private Long id;
    private String name;
    private String url;
    private String imgUrl;

    public Strategy() {
    }

    public Strategy(Long id) {
        this.id = id;
    }

    public Strategy(Long id, String name, String url, String imgUrl) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.imgUrl = imgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
