package com.zhao.giftsaydemo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STRATEGY".
 */
public class Strategy {

    private Long id;
    private Integer channels;
    private String name;
    private String url;
    private String imgUrl;
    private Boolean isLiked;
    private Integer likeCount;

    public Strategy() {
    }

    public Strategy(Long id) {
        this.id = id;
    }

    public Strategy(Long id, Integer channels, String name, String url, String imgUrl, Boolean isLiked, Integer likeCount) {
        this.id = id;
        this.channels = channels;
        this.name = name;
        this.url = url;
        this.imgUrl = imgUrl;
        this.isLiked = isLiked;
        this.likeCount = likeCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getChannels() {
        return channels;
    }

    public void setChannels(Integer channels) {
        this.channels = channels;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Boolean getIsLiked() {
        return isLiked;
    }

    public void setIsLiked(Boolean isLiked) {
        this.isLiked = isLiked;
    }

    public Integer getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

}
